[profile.release]
lto = "fat"
panic = "abort"
strip = "symbols"
codegen-units = 1

[profile.dev-opt]
inherits = "dev"
lto = "thin"
opt-level = 1

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Clink-arg=-fuse-ld=lld",
    "-Ctarget-cpu=native",
    #"-Cforce-frame-pointers=no",
    #"-Cforce-unwind-tables=no"
]
